version: "3.8"
services:
  node:
    container_name: "first-nestjs-project"
    hostname: "host-first-nestjs-project"
    build: .
    entrypoint: sh -c "npm install && npm run start:dev"
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000